### ISSUE TITLE
title

### ISSUE THREAD

**Issue by Pum-purum** [yushkevichv/bitrix-vue-cart#1]
А где сам компонент корзины?

**Comment by yushkevichv** [comment]
https://github.com/yushkevichv/bitrix-vue-cart/tree/master/local/resource/assets/js/components 
Тут доступны все используемые vue компоненты. 

Это был прототип, поэтому делался только основной функционал

**Comment by Pum-purum** [comment]
Я имею в виду, компонент корзины Битрикса. Он как-то модифицировался? Или как мне использовать этот репозиторий?

**Comment by yushkevichv** [comment]
Не понял вопросов. 

страница с корзиной:
https://github.com/yushkevichv/bitrix-vue-cart/blob/master/personal/cart_vue/index.php

Типовой скелетон апи (для production рекомендую использовать полноценное апи с роутингом, напоминаю, что это прототип на проверку возможности работы с vue js)
https://github.com/yushkevichv/bitrix-vue-cart/blob/master/local/api/cart.php

Как это использовать и для чего - каждый решает для себя. Это не готовый модуль, а подтверждение готовности, что стандартный функционал битрикса в части корзины и оформления заказа можно перенести на vue js компоненты нескольким способами. 

Репозиторий носит ознакомительные цели, дальнейшей поддержки корне будет.
